FROM archlinux

RUN pacman -Syu neovim git tmux sudo clang openssh pyright python --noconfirm

RUN useradd -m -s /usr/bin/bash nosiee
RUN echo "nosiee:nosiee" | chpasswd
RUN echo "nosiee ALL=(ALL:ALL) ALL" >> /etc/sudoers

USER nosiee 
WORKDIR /home/nosiee

RUN git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
RUN mkdir ~/.tmux/resurrect

CMD ["/bin/bash"]
