FROM archlinux

RUN pacman -Syu neovim git tmux sudo clang gcc make pkg-config --noconfirm

RUN useradd -m -s /usr/bin/bash nosiee
RUN echo "nosiee:nosiee" | chpasswd
RUN echo "nosiee ALL=(ALL:ALL) ALL" >> /etc/sudoers

USER nosiee 
WORKDIR /home/nosiee

RUN git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

CMD ["tmux"]
