FROM archlinux

RUN pacman -Syu neovim go git tmux sudo gopls --noconfirm
RUN useradd -m -p $(perl -e 'print crypt($ARGV[0], "password")' nosiee) -s /usr/bin/bash nosiee
RUN echo "nosiee ALL=(ALL:ALL) ALL" >> /etc/sudoers

USER nosiee 
WORKDIR /home/nosiee

CMD ["tmux"]
